/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tier = IDL.Variant({
  'a' : IDL.Null,
  'b' : IDL.Null,
  'c' : IDL.Null,
  'd' : IDL.Null,
  's' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tier' : Tier,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'gameMode' : IDL.Text,
  'points' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([Player], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
  'getPlayersByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
  'getPodium' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getTop3Players' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'setPodium' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updatePlayer' : IDL.Func([IDL.Nat, Player], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tier = IDL.Variant({
    'a' : IDL.Null,
    'b' : IDL.Null,
    'c' : IDL.Null,
    'd' : IDL.Null,
    's' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tier' : Tier,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'gameMode' : IDL.Text,
    'points' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func([Player], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
    'getPlayersByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
    'getPodium' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getTop3Players' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'setPodium' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updatePlayer' : IDL.Func([IDL.Nat, Player], [], []),
  });
};

export const init = ({ IDL }) => { return []; };