/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Player {
  'id' : bigint,
  'name' : string,
  'tier' : Tier,
  'avatarUrl' : [] | [string],
  'gameMode' : string,
  'points' : bigint,
}
export type Tier = { 'a' : null } |
  { 'b' : null } |
  { 'c' : null } |
  { 'd' : null } |
  { 's' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[Player], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePlayer' : ActorMethod<[bigint], undefined>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayer' : ActorMethod<[bigint], Player>,
  'getPlayersByTier' : ActorMethod<[Tier], Array<Player>>,
  'getPodium' : ActorMethod<[], Array<Player>>,
  'getTop3Players' : ActorMethod<[], Array<Player>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'setPodium' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updatePlayer' : ActorMethod<[bigint, Player], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];